// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	youtrack "github.com/skynet2/youtrack-mcp/pkg/youtrack"
)

// MockYouTrackClient is a mock of YouTrackClient interface.
type MockYouTrackClient struct {
	ctrl     *gomock.Controller
	recorder *MockYouTrackClientMockRecorder
}

// MockYouTrackClientMockRecorder is the mock recorder for MockYouTrackClient.
type MockYouTrackClientMockRecorder struct {
	mock *MockYouTrackClient
}

// NewMockYouTrackClient creates a new mock instance.
func NewMockYouTrackClient(ctrl *gomock.Controller) *MockYouTrackClient {
	mock := &MockYouTrackClient{ctrl: ctrl}
	mock.recorder = &MockYouTrackClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYouTrackClient) EXPECT() *MockYouTrackClientMockRecorder {
	return m.recorder
}

// ActivityList mocks base method.
func (m *MockYouTrackClient) ActivityList(ctx context.Context, categories, issueQuery, start, end string, skip, top int) ([]youtrack.ActivityItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivityList", ctx, categories, issueQuery, start, end, skip, top)
	ret0, _ := ret[0].([]youtrack.ActivityItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivityList indicates an expected call of ActivityList.
func (mr *MockYouTrackClientMockRecorder) ActivityList(ctx, categories, issueQuery, start, end, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivityList", reflect.TypeOf((*MockYouTrackClient)(nil).ActivityList), ctx, categories, issueQuery, start, end, skip, top)
}

// AgileList mocks base method.
func (m *MockYouTrackClient) AgileList(ctx context.Context, skip, top int) ([]youtrack.Agile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgileList", ctx, skip, top)
	ret0, _ := ret[0].([]youtrack.Agile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgileList indicates an expected call of AgileList.
func (mr *MockYouTrackClientMockRecorder) AgileList(ctx, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgileList", reflect.TypeOf((*MockYouTrackClient)(nil).AgileList), ctx, skip, top)
}

// ArticleCreate mocks base method.
func (m *MockYouTrackClient) ArticleCreate(ctx context.Context, article youtrack.Article) (youtrack.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticleCreate", ctx, article)
	ret0, _ := ret[0].(youtrack.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArticleCreate indicates an expected call of ArticleCreate.
func (mr *MockYouTrackClientMockRecorder) ArticleCreate(ctx, article interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleCreate", reflect.TypeOf((*MockYouTrackClient)(nil).ArticleCreate), ctx, article)
}

// ArticleDelete mocks base method.
func (m *MockYouTrackClient) ArticleDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticleDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArticleDelete indicates an expected call of ArticleDelete.
func (mr *MockYouTrackClientMockRecorder) ArticleDelete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleDelete", reflect.TypeOf((*MockYouTrackClient)(nil).ArticleDelete), ctx, id)
}

// ArticleGet mocks base method.
func (m *MockYouTrackClient) ArticleGet(ctx context.Context, id string) (youtrack.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticleGet", ctx, id)
	ret0, _ := ret[0].(youtrack.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArticleGet indicates an expected call of ArticleGet.
func (mr *MockYouTrackClientMockRecorder) ArticleGet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleGet", reflect.TypeOf((*MockYouTrackClient)(nil).ArticleGet), ctx, id)
}

// ArticleList mocks base method.
func (m *MockYouTrackClient) ArticleList(ctx context.Context, skip, top int) ([]youtrack.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticleList", ctx, skip, top)
	ret0, _ := ret[0].([]youtrack.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArticleList indicates an expected call of ArticleList.
func (mr *MockYouTrackClientMockRecorder) ArticleList(ctx, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleList", reflect.TypeOf((*MockYouTrackClient)(nil).ArticleList), ctx, skip, top)
}

// ArticleUpdate mocks base method.
func (m *MockYouTrackClient) ArticleUpdate(ctx context.Context, id string, article youtrack.Article) (youtrack.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticleUpdate", ctx, id, article)
	ret0, _ := ret[0].(youtrack.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArticleUpdate indicates an expected call of ArticleUpdate.
func (mr *MockYouTrackClientMockRecorder) ArticleUpdate(ctx, id, article interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleUpdate", reflect.TypeOf((*MockYouTrackClient)(nil).ArticleUpdate), ctx, id, article)
}

// CommentCreate mocks base method.
func (m *MockYouTrackClient) CommentCreate(ctx context.Context, issueID string, comment youtrack.IssueComment) (youtrack.IssueComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentCreate", ctx, issueID, comment)
	ret0, _ := ret[0].(youtrack.IssueComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentCreate indicates an expected call of CommentCreate.
func (mr *MockYouTrackClientMockRecorder) CommentCreate(ctx, issueID, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentCreate", reflect.TypeOf((*MockYouTrackClient)(nil).CommentCreate), ctx, issueID, comment)
}

// CommentDelete mocks base method.
func (m *MockYouTrackClient) CommentDelete(ctx context.Context, issueID, commentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentDelete", ctx, issueID, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommentDelete indicates an expected call of CommentDelete.
func (mr *MockYouTrackClientMockRecorder) CommentDelete(ctx, issueID, commentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentDelete", reflect.TypeOf((*MockYouTrackClient)(nil).CommentDelete), ctx, issueID, commentID)
}

// CommentList mocks base method.
func (m *MockYouTrackClient) CommentList(ctx context.Context, issueID string, skip, top int) ([]youtrack.IssueComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentList", ctx, issueID, skip, top)
	ret0, _ := ret[0].([]youtrack.IssueComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentList indicates an expected call of CommentList.
func (mr *MockYouTrackClientMockRecorder) CommentList(ctx, issueID, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentList", reflect.TypeOf((*MockYouTrackClient)(nil).CommentList), ctx, issueID, skip, top)
}

// CommentUpdate mocks base method.
func (m *MockYouTrackClient) CommentUpdate(ctx context.Context, issueID, commentID string, comment youtrack.IssueComment) (youtrack.IssueComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentUpdate", ctx, issueID, commentID, comment)
	ret0, _ := ret[0].(youtrack.IssueComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentUpdate indicates an expected call of CommentUpdate.
func (mr *MockYouTrackClientMockRecorder) CommentUpdate(ctx, issueID, commentID, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentUpdate", reflect.TypeOf((*MockYouTrackClient)(nil).CommentUpdate), ctx, issueID, commentID, comment)
}

// IssueActivityList mocks base method.
func (m *MockYouTrackClient) IssueActivityList(ctx context.Context, issueID, categories string, skip, top int) ([]youtrack.ActivityItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueActivityList", ctx, issueID, categories, skip, top)
	ret0, _ := ret[0].([]youtrack.ActivityItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueActivityList indicates an expected call of IssueActivityList.
func (mr *MockYouTrackClientMockRecorder) IssueActivityList(ctx, issueID, categories, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueActivityList", reflect.TypeOf((*MockYouTrackClient)(nil).IssueActivityList), ctx, issueID, categories, skip, top)
}

// IssueAddTag mocks base method.
func (m *MockYouTrackClient) IssueAddTag(ctx context.Context, issueID, tagID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAddTag", ctx, issueID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IssueAddTag indicates an expected call of IssueAddTag.
func (mr *MockYouTrackClientMockRecorder) IssueAddTag(ctx, issueID, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAddTag", reflect.TypeOf((*MockYouTrackClient)(nil).IssueAddTag), ctx, issueID, tagID)
}

// IssueCreate mocks base method.
func (m *MockYouTrackClient) IssueCreate(ctx context.Context, issue youtrack.Issue) (youtrack.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueCreate", ctx, issue)
	ret0, _ := ret[0].(youtrack.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueCreate indicates an expected call of IssueCreate.
func (mr *MockYouTrackClientMockRecorder) IssueCreate(ctx, issue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueCreate", reflect.TypeOf((*MockYouTrackClient)(nil).IssueCreate), ctx, issue)
}

// IssueCustomFields mocks base method.
func (m *MockYouTrackClient) IssueCustomFields(ctx context.Context, issueID string) ([]youtrack.IssueCustomField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueCustomFields", ctx, issueID)
	ret0, _ := ret[0].([]youtrack.IssueCustomField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueCustomFields indicates an expected call of IssueCustomFields.
func (mr *MockYouTrackClientMockRecorder) IssueCustomFields(ctx, issueID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueCustomFields", reflect.TypeOf((*MockYouTrackClient)(nil).IssueCustomFields), ctx, issueID)
}

// IssueDelete mocks base method.
func (m *MockYouTrackClient) IssueDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IssueDelete indicates an expected call of IssueDelete.
func (mr *MockYouTrackClientMockRecorder) IssueDelete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueDelete", reflect.TypeOf((*MockYouTrackClient)(nil).IssueDelete), ctx, id)
}

// IssueGet mocks base method.
func (m *MockYouTrackClient) IssueGet(ctx context.Context, id string) (youtrack.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueGet", ctx, id)
	ret0, _ := ret[0].(youtrack.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueGet indicates an expected call of IssueGet.
func (mr *MockYouTrackClientMockRecorder) IssueGet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueGet", reflect.TypeOf((*MockYouTrackClient)(nil).IssueGet), ctx, id)
}

// IssueGetLinks mocks base method.
func (m *MockYouTrackClient) IssueGetLinks(ctx context.Context, issueID string) ([]youtrack.IssueLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueGetLinks", ctx, issueID)
	ret0, _ := ret[0].([]youtrack.IssueLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueGetLinks indicates an expected call of IssueGetLinks.
func (mr *MockYouTrackClientMockRecorder) IssueGetLinks(ctx, issueID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueGetLinks", reflect.TypeOf((*MockYouTrackClient)(nil).IssueGetLinks), ctx, issueID)
}

// IssueRemoveTag mocks base method.
func (m *MockYouTrackClient) IssueRemoveTag(ctx context.Context, issueID, tagID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueRemoveTag", ctx, issueID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IssueRemoveTag indicates an expected call of IssueRemoveTag.
func (mr *MockYouTrackClientMockRecorder) IssueRemoveTag(ctx, issueID, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueRemoveTag", reflect.TypeOf((*MockYouTrackClient)(nil).IssueRemoveTag), ctx, issueID, tagID)
}

// IssueSearch mocks base method.
func (m *MockYouTrackClient) IssueSearch(ctx context.Context, query string, skip, top int) ([]youtrack.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueSearch", ctx, query, skip, top)
	ret0, _ := ret[0].([]youtrack.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueSearch indicates an expected call of IssueSearch.
func (mr *MockYouTrackClientMockRecorder) IssueSearch(ctx, query, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueSearch", reflect.TypeOf((*MockYouTrackClient)(nil).IssueSearch), ctx, query, skip, top)
}

// IssueUpdate mocks base method.
func (m *MockYouTrackClient) IssueUpdate(ctx context.Context, id string, issue youtrack.Issue) (youtrack.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueUpdate", ctx, id, issue)
	ret0, _ := ret[0].(youtrack.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueUpdate indicates an expected call of IssueUpdate.
func (mr *MockYouTrackClientMockRecorder) IssueUpdate(ctx, id, issue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueUpdate", reflect.TypeOf((*MockYouTrackClient)(nil).IssueUpdate), ctx, id, issue)
}

// IssueUpdateField mocks base method.
func (m *MockYouTrackClient) IssueUpdateField(ctx context.Context, issueID, fieldID string, field youtrack.IssueCustomField) (youtrack.IssueCustomField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueUpdateField", ctx, issueID, fieldID, field)
	ret0, _ := ret[0].(youtrack.IssueCustomField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueUpdateField indicates an expected call of IssueUpdateField.
func (mr *MockYouTrackClientMockRecorder) IssueUpdateField(ctx, issueID, fieldID, field interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueUpdateField", reflect.TypeOf((*MockYouTrackClient)(nil).IssueUpdateField), ctx, issueID, fieldID, field)
}

// ProjectGet mocks base method.
func (m *MockYouTrackClient) ProjectGet(ctx context.Context, id string) (youtrack.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectGet", ctx, id)
	ret0, _ := ret[0].(youtrack.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectGet indicates an expected call of ProjectGet.
func (mr *MockYouTrackClientMockRecorder) ProjectGet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectGet", reflect.TypeOf((*MockYouTrackClient)(nil).ProjectGet), ctx, id)
}

// ProjectList mocks base method.
func (m *MockYouTrackClient) ProjectList(ctx context.Context, skip, top int) ([]youtrack.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectList", ctx, skip, top)
	ret0, _ := ret[0].([]youtrack.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectList indicates an expected call of ProjectList.
func (mr *MockYouTrackClientMockRecorder) ProjectList(ctx, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectList", reflect.TypeOf((*MockYouTrackClient)(nil).ProjectList), ctx, skip, top)
}

// SprintGet mocks base method.
func (m *MockYouTrackClient) SprintGet(ctx context.Context, agileID, sprintID string) (youtrack.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SprintGet", ctx, agileID, sprintID)
	ret0, _ := ret[0].(youtrack.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SprintGet indicates an expected call of SprintGet.
func (mr *MockYouTrackClientMockRecorder) SprintGet(ctx, agileID, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SprintGet", reflect.TypeOf((*MockYouTrackClient)(nil).SprintGet), ctx, agileID, sprintID)
}

// SprintList mocks base method.
func (m *MockYouTrackClient) SprintList(ctx context.Context, agileID string, skip, top int) ([]youtrack.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SprintList", ctx, agileID, skip, top)
	ret0, _ := ret[0].([]youtrack.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SprintList indicates an expected call of SprintList.
func (mr *MockYouTrackClientMockRecorder) SprintList(ctx, agileID, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SprintList", reflect.TypeOf((*MockYouTrackClient)(nil).SprintList), ctx, agileID, skip, top)
}

// TagList mocks base method.
func (m *MockYouTrackClient) TagList(ctx context.Context, skip, top int) ([]youtrack.IssueTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagList", ctx, skip, top)
	ret0, _ := ret[0].([]youtrack.IssueTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagList indicates an expected call of TagList.
func (mr *MockYouTrackClientMockRecorder) TagList(ctx, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagList", reflect.TypeOf((*MockYouTrackClient)(nil).TagList), ctx, skip, top)
}

// UserCurrent mocks base method.
func (m *MockYouTrackClient) UserCurrent(ctx context.Context) (youtrack.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserCurrent", ctx)
	ret0, _ := ret[0].(youtrack.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserCurrent indicates an expected call of UserCurrent.
func (mr *MockYouTrackClientMockRecorder) UserCurrent(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserCurrent", reflect.TypeOf((*MockYouTrackClient)(nil).UserCurrent), ctx)
}

// UserList mocks base method.
func (m *MockYouTrackClient) UserList(ctx context.Context, query string, skip, top int) ([]youtrack.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserList", ctx, query, skip, top)
	ret0, _ := ret[0].([]youtrack.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserList indicates an expected call of UserList.
func (mr *MockYouTrackClientMockRecorder) UserList(ctx, query, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserList", reflect.TypeOf((*MockYouTrackClient)(nil).UserList), ctx, query, skip, top)
}

// WorkItemCreate mocks base method.
func (m *MockYouTrackClient) WorkItemCreate(ctx context.Context, issueID string, item youtrack.IssueWorkItem) (youtrack.IssueWorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkItemCreate", ctx, issueID, item)
	ret0, _ := ret[0].(youtrack.IssueWorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkItemCreate indicates an expected call of WorkItemCreate.
func (mr *MockYouTrackClientMockRecorder) WorkItemCreate(ctx, issueID, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkItemCreate", reflect.TypeOf((*MockYouTrackClient)(nil).WorkItemCreate), ctx, issueID, item)
}

// WorkItemList mocks base method.
func (m *MockYouTrackClient) WorkItemList(ctx context.Context, issueID string, skip, top int) ([]youtrack.IssueWorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkItemList", ctx, issueID, skip, top)
	ret0, _ := ret[0].([]youtrack.IssueWorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkItemList indicates an expected call of WorkItemList.
func (mr *MockYouTrackClientMockRecorder) WorkItemList(ctx, issueID, skip, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkItemList", reflect.TypeOf((*MockYouTrackClient)(nil).WorkItemList), ctx, issueID, skip, top)
}
